<?php
/**
 * ACF Fields for Pinnacle Portal
 *
 * This file contains the ACF field definitions for the Pinnacle Portal theme.
 * It will only be loaded if ACF is active.
 */

if (!function_exists('acf_add_local_field_group')) {
    return;
}

/**
 * Dealer Fields
 */
acf_add_local_field_group(array(
    'key' => 'group_dealer_info',
    'title' => 'Dealer Information',
    'fields' => array(
        array(
            'key' => 'field_dealer_phone',
            'label' => 'Phone Number',
            'name' => 'dealer_phone',
            'type' => 'text',
            'instructions' => 'Enter the dealer\'s phone number',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_dealer_email',
            'label' => 'Email Address',
            'name' => 'dealer_email',
            'type' => 'email',
            'instructions' => 'Enter the dealer\'s email address',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_dealer_address',
            'label' => 'Address',
            'name' => 'dealer_address',
            'type' => 'textarea',
            'instructions' => 'Enter the dealer\'s address',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_dealer_website',
            'label' => 'Website',
            'name' => 'dealer_website',
            'type' => 'url',
            'instructions' => 'Enter the dealer\'s website URL',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        array(
            'key' => 'field_dealer_contact_name',
            'label' => 'Contact Name',
            'name' => 'dealer_contact_name',
            'type' => 'text',
            'instructions' => 'Enter the name of the primary contact',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'dealer',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

/**
 * Deal Fields
 */
acf_add_local_field_group(array(
    'key' => 'group_deal_info',
    'title' => 'Deal Information',
    'fields' => array(
        array(
            'key' => 'field_related_dealer',
            'label' => 'Related Dealer',
            'name' => 'related_dealer',
            'type' => 'post_object',
            'instructions' => 'Select the dealer associated with this deal',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'dealer',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'id',
            'ui' => 1,
        ),
        array(
            'key' => 'field_deal_amount',
            'label' => 'Deal Amount',
            'name' => 'deal_amount',
            'type' => 'number',
            'instructions' => 'Enter the total amount of the deal',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '$',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        array(
            'key' => 'field_deal_date',
            'label' => 'Deal Date',
            'name' => 'deal_date',
            'type' => 'date_picker',
            'instructions' => 'Select the date of the deal',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'm/d/Y',
            'return_format' => 'm/d/Y',
            'first_day' => 0,
        ),
        array(
            'key' => 'field_deal_notes',
            'label' => 'Deal Notes',
            'name' => 'deal_notes',
            'type' => 'textarea',
            'instructions' => 'Enter any notes about this deal',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 6,
            'new_lines' => 'wpautop',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'deal',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

/**
 * Customer Fields
 */
acf_add_local_field_group(array(
    'key' => 'group_customer_info',
    'title' => 'Customer Information',
    'fields' => array(
        array(
            'key' => 'field_customer_name',
            'label' => 'Customer Name',
            'name' => 'customer_name',
            'type' => 'text',
            'instructions' => 'Enter the customer\'s full name',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_customer_phone',
            'label' => 'Phone Number',
            'name' => 'customer_phone',
            'type' => 'text',
            'instructions' => 'Enter the customer\'s phone number',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_customer_email',
            'label' => 'Email Address',
            'name' => 'customer_email',
            'type' => 'email',
            'instructions' => 'Enter the customer\'s email address',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_customer_address',
            'label' => 'Address',
            'name' => 'customer_address',
            'type' => 'textarea',
            'instructions' => 'Enter the customer\'s address',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'br',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'deal',
            ),
        ),
    ),
    'menu_order' => 10,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

/**
 * Vehicle Fields
 */
acf_add_local_field_group(array(
    'key' => 'group_vehicle_info',
    'title' => 'Vehicle Information',
    'fields' => array(
        array(
            'key' => 'field_vehicle_make',
            'label' => 'Make',
            'name' => 'vehicle_make',
            'type' => 'text',
            'instructions' => 'Enter the vehicle make',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_vehicle_model',
            'label' => 'Model',
            'name' => 'vehicle_model',
            'type' => 'text',
            'instructions' => 'Enter the vehicle model',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_vehicle_year',
            'label' => 'Year',
            'name' => 'vehicle_year',
            'type' => 'number',
            'instructions' => 'Enter the vehicle year',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => 1900,
            'max' => 2100,
            'step' => 1,
        ),
        array(
            'key' => 'field_vehicle_vin',
            'label' => 'VIN',
            'name' => 'vehicle_vin',
            'type' => 'text',
            'instructions' => 'Enter the vehicle identification number',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '67',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => 17,
        ),
        array(
            'key' => 'field_vehicle_mileage',
            'label' => 'Mileage',
            'name' => 'vehicle_mileage',
            'type' => 'number',
            'instructions' => 'Enter the vehicle mileage',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => 'miles',
            'min' => 0,
            'max' => '',
            'step' => 1,
        ),
        array(
            'key' => 'field_vehicle_price',
            'label' => 'Price',
            'name' => 'vehicle_price',
            'type' => 'number',
            'instructions' => 'Enter the vehicle price',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '$',
            'append' => '',
            'min' => 0,
            'max' => '',
            'step' => 0.01,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'deal',
            ),
        ),
    ),
    'menu_order' => 20,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
