version: '3'
services:
  strapi:
    image: strapi/strapi:latest
    ports:
      - '1337:1337'
    volumes:
      - ./app:/srv/app
    environment:
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
